// Pins the root-index generator's contract: the page lists ONLY branches/dev/
// and the latest demo/<tag>/ (nothing of the old hand-authored landing page —
// no showcase, no prose links), links only what exists (root index.html vs the
// de/, en/, qa.html entry points), orders demo tags by real SemVer
// (v0.10.0 > v0.9.9), degrades cleanly when dev or the demo does not exist
// yet, and always carries the do-not-edit + deliberately-unlisted comments.
//
// Run with:  node --test scripts/gen-pages-index.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  compareSemver,
  discoverTree,
  generateIndex,
  highestSemverTag,
  main,
} from "./gen-pages-index.mjs";

const BASE = {
  repo: "ig-template-mii-kds",
  repoUrl: "https://github.com/medizininformatik-initiative/ig-template-mii-kds",
};

function hrefs(html) {
  return [...html.matchAll(/href="([^"]*)"/g)].map((m) => m[1]);
}

test("normal case: dev preview + latest demo with a root index.html", () => {
  const html = generateIndex({ ...BASE, dev: true, demoTag: "v1.3.3", demoEntries: ["index.html"] });
  assert.match(html, /<a href="branches\/dev\/">branches\/dev\/<\/a>/);
  assert.match(html, /<a href="demo\/v1\.3\.3\/">demo\/v1\.3\.3\/<\/a>/);
  // The header line names the repo and links the MII repository.
  assert.match(
    html,
    /<a href="https:\/\/github\.com\/medizininformatik-initiative\/ig-template-mii-kds">ig-template-mii-kds<\/a>/,
  );
  assert.match(html, /<title>ig-template-mii-kds<\/title>/);
  // Exactly three links: header, dev preview, demo — nothing else.
  assert.deepEqual(hrefs(html), [
    "https://github.com/medizininformatik-initiative/ig-template-mii-kds",
    "branches/dev/",
    "demo/v1.3.3/",
  ]);
});

test("demo without a root index.html lists its real entry points as sub-links", () => {
  const html = generateIndex({
    ...BASE,
    dev: true,
    demoTag: "v1.3.3",
    demoEntries: ["de/", "en/", "qa.html"],
  });
  assert.match(html, /<a href="demo\/v1\.3\.3\/de\/">de\/<\/a>/);
  assert.match(html, /<a href="demo\/v1\.3\.3\/en\/">en\/<\/a>/);
  assert.match(html, /<a href="demo\/v1\.3\.3\/qa\.html">qa\.html<\/a>/);
  // The tag directory itself must NOT be linked — it has no index to serve.
  assert.ok(!hrefs(html).includes("demo/v1.3.3/"));
});

test("no dev preview yet: branches/dev/ is not listed", () => {
  const html = generateIndex({ ...BASE, dev: false, demoTag: "v1.3.3", demoEntries: ["index.html"] });
  assert.doesNotMatch(html, /branches\/dev/);
  assert.match(html, /demo\/v1\.3\.3\//);
});

test("no demo yet: only the dev preview is listed", () => {
  const html = generateIndex({ ...BASE, dev: true, demoTag: null });
  assert.ok(!hrefs(html).some((href) => href.startsWith("demo/")));
  assert.match(html, /<a href="branches\/dev\/">/);
});

test("nothing deployed yet: the page still renders, with no dead links", () => {
  const html = generateIndex({ ...BASE, dev: false, demoTag: null });
  assert.match(html, /Nothing deployed yet\./);
  assert.deepEqual(hrefs(html), [BASE.repoUrl]);
});

test("semver ordering is numeric per field: v0.10.0 > v0.9.9", () => {
  assert.equal(highestSemverTag(["v0.9.9", "v0.10.0"]), "v0.10.0");
  assert.equal(highestSemverTag(["v0.10.0", "v1.3.3", "v0.5.1"]), "v1.3.3");
  // A pre-release sorts below its release, above the previous release.
  assert.ok(compareSemver("v1.4.0-rc.1", "v1.4.0") < 0);
  assert.ok(compareSemver("v1.4.0-rc.1", "v1.3.3") > 0);
  assert.ok(compareSemver("v1.4.0-rc.2", "v1.4.0-rc.10") < 0);
  // Non-tag directory names are ignored, an empty set yields null.
  assert.equal(highestSemverTag(["latest", "not-a-tag"]), null);
  assert.equal(highestSemverTag([]), null);
});

test("the old landing-page content is gone: no showcase, no prose links", () => {
  const html = generateIndex({ ...BASE, dev: true, demoTag: "v1.3.3", demoEntries: ["index.html"] });
  for (const remnant of [/showcase/i, /sandbox/i, /Rendered demo/, /release notes/i, /Forschungsgruppe/i]) {
    assert.doesNotMatch(html, remnant);
  }
});

test("every page carries the do-not-edit marker and the deliberately-unlisted comment", () => {
  for (const options of [
    { ...BASE, dev: true, demoTag: "v1.3.3", demoEntries: ["index.html"] },
    { ...BASE, dev: false, demoTag: null },
  ]) {
    const html = generateIndex(options);
    assert.match(html, /generated by scripts\/gen-pages-index\.mjs - do not edit by hand/);
    assert.match(html, /deliberately unlisted/);
  }
});

test("discovery + main() against a fixture tree: picks the highest tag, finds the entry points, writes the index", () => {
  const root = mkdtempSync(join(tmpdir(), "gen-pages-index-"));
  try {
    // branches: dev plus an unrelated preview that must stay unlisted.
    mkdirSync(join(root, "branches", "dev"), { recursive: true });
    writeFileSync(join(root, "branches", "dev", "index.html"), "dev");
    mkdirSync(join(root, "branches", "feature", "x"), { recursive: true });
    // demos: v0.9.9 has a root index; the HIGHER v0.10.0 has only entry points.
    mkdirSync(join(root, "demo", "v0.9.9"), { recursive: true });
    writeFileSync(join(root, "demo", "v0.9.9", "index.html"), "old");
    for (const language of ["de", "en"]) {
      mkdirSync(join(root, "demo", "v0.10.0", language), { recursive: true });
      writeFileSync(join(root, "demo", "v0.10.0", language, "index.html"), language);
    }
    writeFileSync(join(root, "demo", "v0.10.0", "qa.html"), "qa");

    const state = discoverTree(root);
    assert.deepEqual(state, { dev: true, demoTag: "v0.10.0", demoEntries: ["de/", "en/", "qa.html"] });

    assert.equal(main([root]), 0);
    const html = readFileSync(join(root, "index.html"), "utf8");
    assert.match(html, /demo\/v0\.10\.0\/de\//);
    assert.doesNotMatch(html, /v0\.9\.9/);
    assert.doesNotMatch(html, /branches\/feature/);

    // Regenerating over the just-written index is stable and does not list itself.
    assert.equal(main([root]), 0);
    assert.equal(readFileSync(join(root, "index.html"), "utf8"), html);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("main() rejects a missing or non-directory path", () => {
  assert.equal(main([]), 2);
  assert.equal(main([join(tmpdir(), "gen-pages-index-does-not-exist")]), 2);
});
